# fly.toml (Ana Dizinde - DÜZELTİLMİŞ)
app = 'belgehizli-api'
primary_region = 'fra'

[build]
  dockerfile = 'backend/Dockerfile'

# HTTP ve HTTPS portlarını tek bir servis bloğunda tanımla
[[services]]
  internal_port = 8080 # Kodunuzun process.env.PORT'tan alıp dinlediği port
  protocol = 'tcp'
  processes = ['app']

  # HTTP (Port 80) ayarları
  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true # Gelen HTTP isteklerini HTTPS'e yönlendir

  # HTTPS (Port 443) ayarları
  [[services.ports]]
    port = 443
    handlers = ['tls', 'http'] # TLS sonlandırma ve HTTP işleme

  # Opsiyonel: Sağlık kontrolü
  # [[services.http_checks]]
  #  interval = "10s"
  #  timeout = "2s"
  #  grace_period = "5s"
  #  method = "get"
  #  path = "/api/test" # Test endpoint'iniz
  #  protocol = "http" # İç port HTTP olduğu için

  # VM ayarları
  [[vm]]
    memory = '1gb' # Veya Fly.io'nun desteklediği daha küçük bir boyut (örn: '256mb')
    cpu_kind = 'shared'
    cpus = 1